development:
   adapter: async

test:
   adapter: test

production:
   adapter: redis
   url: redis://redistogo:4e296a2ff3a4560f54a5ed92d27a4f5e@sole.redistogo.com:9385/
   channel_prefix: phase_4_project_guidelines_production
